logging:
   level:
      org.springframework: info
currency-service:
   url: http://sajin.paramel.com
   username: vishnupriya
   key: paaru
management:
   endpoints:
      web:
         exposure:
            include: "*"